aliases:
#  Xcode version announcments can be found here: https://discuss.circleci.com/c/announcements/
#  Each post contains a full image manifest, including iOS runtimes, devices, CocoaPods version, etc.
#  NOTE: When updaing Xcode check the manifest for compatible chruby versions.
  - &latest-xcode "13.4.1"
  - &beta-xcode "14.0.0"

  - &upgrade-cocoapods
    name: Upgrade Cocoapods
    command:  |
      sudo gem install cocoapods -v 1.10.1

  - &setup
    name: Setup
    command: node ./install.js
    when: always

  - &install-cordova
    name: Install Cordova
    command:  |
      if [[ "$OSTYPE" == "linux-gnu" ]]; then
        sudo npm install -g cordova@11.0.0
      else 
        npm update -g
        npm install -g cordova@11.0.0
      fi
      sudo cordova telemetry off
    when: always

  - &install-sfdx
    name: Install SFDX
    command: |
      if [[ "$OSTYPE" == "linux-gnu" ]]; then
        sudo npm install -g sfdx-cli
      else 
        npm install -g sfdx-cli
      fi
    when: always

  - &install-typescript
    name: Install Typescript
    command: |
      if [[ "$OSTYPE" == "linux-gnu" ]]; then
        sudo npm install -g typescript
      else 
        npm install -g typescript
      fi
    when: always

version: 2.1
executors:
  linux:
    working_directory: ~/SalesforceMobileSDK-Package
    docker:
      - image: cimg/android:2022.08.1-node
    environment:
      - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
  mac:
    working_directory: ~/SalesforceMobileSDK-Package
    macos:
      xcode: *latest-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
  mac-beta:
    working_directory: ~/SalesforceMobileSDK-Package
    macos:
      xcode: *beta-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"

jobs:
  forcedroid:
    executor: linux
    steps:
      - checkout
      - run: *setup
      - run:
          name: Building all android native templates
          command:  ./test/test_force.js --exit-on-failure --cli=forcedroid
          when: always

  forcedroid-sfdx:
    executor: linux
    steps:
      - checkout
      - run: *setup
      - run: *install-sfdx
      - run:
          name: Building all android native templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcedroid --use-sfdx
          when: always

  forcehybrid-android:
    executor: linux
    steps:
      - checkout
      - run: *setup
      - run: *install-cordova
      - run: *install-sfdx
      - run:
          name: Building all android hybrid templates
          command: ./test/test_force.js --exit-on-failure --cli=forcehybrid --os=android --no-plugin-update
          when: always

  forcehybrid-android-sfdx:
    executor: linux
    steps:
      - checkout
      - run: *setup
      - run: *install-cordova
      - run: *install-sfdx
      - run:
          name: Building all android hybrid templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcehybrid --os=android --use-sfdx --no-plugin-update
          when: always

  forcereact-android:
    executor: linux
    steps:
      - checkout
      - run: *setup
      - run: *install-typescript
      - run:
          name: Building all android react native templates
          command: ./test/test_force.js --exit-on-failure --cli=forcereact --os=android
          when: always

  forcereact-android-sfdx:
    executor: linux
    steps:
      - checkout
      - run: *setup
      - run: *install-sfdx
      - run: *install-typescript
      - run:
          name: Building all android react native templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcereact --os=android --use-sfdx
          when: always

  forceios:
    parameters:
      env:
        type: string
        default: "mac"
    executor: << parameters.env >>
    steps:
      - checkout
      - run: *setup
      - run: *upgrade-cocoapods
      - run:
          name: Building all ios native templates
          command:  ./test/test_force.js --exit-on-failure --cli=forceios
          when: always

  forceios-sfdx:
    parameters:
      env:
        type: string
        default: "mac"
    executor: << parameters.env >>
    steps:
      - checkout
      - run: *setup
      - run: *upgrade-cocoapods
      - run: *install-sfdx
      - run:
          name: Building all ios native templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forceios --use-sfdx
          when: always

  forcehybrid-ios:
    parameters:
      env:
        type: string
        default: "mac"
    executor: << parameters.env >>
    steps:
      - checkout
      - run: *setup
      - run: *upgrade-cocoapods
      - run: *install-cordova
      - run: *install-sfdx
      - run:
          name: Building all ios hybrid templates
          command:  |
              sudo chown -R `whoami` /Users/`whoami`/Library/Preferences/
              ./test/test_force.js --exit-on-failure --cli=forcehybrid --os=ios --no-plugin-update
          when: always

  forcehybrid-ios-sfdx:
    parameters:
      env:
        type: string
        default: "mac"
    executor: << parameters.env >>
    steps:
      - checkout
      - run: *setup
      - run: *upgrade-cocoapods
      - run: *install-cordova
      - run: *install-sfdx
      - run:
          name: Building all ios hybrid templates with SFDX
          command:  |
              sudo chown -R `whoami` /Users/`whoami`/Library/Preferences/
              ./test/test_force.js --exit-on-failure --cli=forcehybrid --os=ios --use-sfdx --no-plugin-update
          when: always

  forcereact-ios:
    parameters:
      env:
        type: string
        default: "mac"
    executor: << parameters.env >>
    steps:
      - checkout
      - run: *setup
      - run: *upgrade-cocoapods
      - run: *install-typescript
      - run:
          name: Building all ios react native templates
          command: ./test/test_force.js --exit-on-failure --cli=forcereact --os=ios
          when: always

  forcereact-ios-sfdx:
    parameters:
      env:
        type: string
        default: "mac"
    executor: << parameters.env >>
    steps:
      - checkout
      - run: *setup
      - run: *upgrade-cocoapods
      - run: *install-sfdx
      - run: *install-typescript
      - run:
          name: Building all ios react native templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcereact --os=ios --use-sfdx
          when: always

#  Potential parameters that can come from the project GUI Triggers
parameters:
  beta:
    type: boolean
    default: false

workflows:
  version: 2

  pr-build-all-apps:
    when: 
      equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - forceios
      - forcehybrid-ios
      - forcereact-ios
      - forcedroid
      - forcehybrid-android
      - forcereact-android
      - forceios-sfdx
      - forcehybrid-ios-sfdx
      - forcereact-ios-sfdx
      - forcedroid-sfdx
      - forcehybrid-android-sfdx
      - forcereact-android-sfdx

  # Build everything at 8:00 PM PST Wednesday and Sunday
  weekly-build-all-apps:
    when: 
      not:
        equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - forceios
      - forcehybrid-ios
      - forcereact-ios
      - forcedroid
      - forcehybrid-android
      - forcereact-android
      - forceios-sfdx
      - forcehybrid-ios-sfdx
      - forcereact-ios-sfdx
      - forcedroid-sfdx
      - forcehybrid-android-sfdx
      - forcereact-android-sfdx

  # Build everything iOS wtih Beta Xcode at 9:00 PM PST Wednesday and Sunday
  weekly-build-all-apps-ios-beta:
    when: 
      and:
        - << pipeline.parameters.beta >>
        - not:
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - forceios:
          env: "mac-beta"
      - forcehybrid-ios:
          env: "mac-beta"
      - forcereact-ios:
          env: "mac-beta"
      - forceios-sfdx:
          env: "mac-beta"
      - forcehybrid-ios-sfdx:
          env: "mac-beta"
      - forcereact-ios-sfdx:
          env: "mac-beta"