aliases:
  - &upgrade-git
    name: Update Git
    command:  |
      git --version
      sudo apt-get install \
        build-essential flex bison \
        libreadline6-dev zlib1g-dev \
        libssl-dev \
        libcurl4-gnutls-dev \
        libexpat1-dev \
        tcl tk \
        tcl-dev gettext \
        asciidoc \
        docbook2x

      wget https://www.kernel.org/pub/software/scm/git/git-2.13.0.tar.gz
      tar -xvzf git-2.13.0.tar.gz
      cd git-2.13.0
      sudo ./configure
      sudo make && sudo make install
      git --version

  - &downgrade-cocoapods
    name: Downgrade to CocoaPods 1.4
    command:  |
      echo Y | sudo gem uninstall cocoapods
      sudo gem install cocoapods -v 1.4
    when: always

  - &setup
    name: Setup
    command: node ./install.js
    when: always

  - &ios-cordova
    name: Install Cordova
    command:  |
      npm install -g cordova@8.0.0
      cordova telemetry off

  - &android-cordova
    name: Install Cordova
    command:  |
      sudo npm install -g cordova@8.0.0
      sudo cordova telemetry off

  - &install-ant
    name: Install Ant
    command: brew install ant

  - &install-sfdx
    name: Install SFDX
    command: sudo npm install -g sfdx-cli
    when: always

linux: &linux
  working_directory: ~/SalesforceMobileSDK-Package
  docker:
    - image: circleci/android:api-28-node8-alpha
  environment:
    - TERM: "dumb"
    - ADB_INSTALL_TIMEOUT: 15
    - _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    - GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
    - ANDROID_NDK: '/opt/ndk/android-ndk-r10e'
    - BUILD_THREADS: 2

mac: &mac
  working_directory: ~/SalesforceMobileSDK-Package
  macos:
    xcode: "10.0.0"
  shell: /bin/bash --login -eo pipefail

version: 2
jobs:
  build-forcedroid:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run: *install-sfdx
      - run:
          name: Building all android native templates
          command: |
            ! ( ./test/test_force.js --cli=forcedroid | grep -q "!FAILURE!" )
          when: always
      - run:
          name: Building all android native templates with SFDX
          command: |
            ! ( ./test/test_force.js --cli=forcedroid --use-sfdx | grep -q "!FAILURE!" )
          when: always

  build-forcehybrid-android:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run: *android-cordova
      - run: *install-sfdx
      - run:
          name: Building all android hybrid templates
          command: |
            ! ( ./test/test_force.js --cli=forcehybrid --os=android | grep -q "!FAILURE!" )
          when: always
      - run:
          name: Building all android hybrid templates with SFDX
          command: |
            ! ( ./test/test_force.js --cli=forcehybrid --os=android --use-sfdx | grep -q "!FAILURE!" )
          when: always

  build-forcereact-android:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run: *install-sfdx
      - run:
          name: Building all android react native templates
          command: |
            ! ( ./test/test_force.js --cli=forcereact --os=android | grep -q "!FAILURE!" )
          when: always
      - run:
          name: Building all android react native templates with SFDX
          command: |
            ! ( ./test/test_force.js --cli=forcereact --os=android --use-sfdx | grep -q "!FAILURE!" )
          when: always

  build-forceios:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *install-ant
      - run: *downgrade-cocoapods
      - run: *install-sfdx
      - run:
          name: Building all ios native templates
          command: |
            ! ( ./test/test_force.js --cli=forceios | grep -q "!FAILURE!" )
          when: always
      - run:
          name: Building all ios native templates with SFDX
          command: |
            ! ( ./test/test_force.js --cli=forceios --use-sfdx | grep -q "!FAILURE!" )
          when: always

  build-forcehybrid-ios:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *install-ant
      - run: *install-sfdx
      - run:
          name: Building all ios hybrid templates
          command: |
            ! ( ./test/test_force.js --cli=forcehybrid --os=ios | grep -q "!FAILURE!" )
          when: always
      - run:
          name: Building all ios hybrid templates with SFDX
          command: |
            ! ( ./test/test_force.js --cli=forcehybrid --os=ios --use-sfdx | grep -q "!FAILURE!" )
          when: always

  build-forcereact-ios:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *install-ant
      - run: *downgrade-cocoapods
      - run: *install-sfdx
      - run:
          name: Building all ios react native templates
          command: |
            ! ( ./test/test_force.js --cli=forcereact --os=ios | grep -q "!FAILURE!" )
          when: always
      - run:
          name: Building all ios react native templates with SFDX
          command: |
            ! ( ./test/test_force.js --cli=forcereact --os=ios --use-sfdx | grep -q "!FAILURE!" )
          when: always

workflows:
  version: 2

  pr-build-all-apps:
    jobs:
      - build-forcedroid
      - build-forcehybrid-android
      - build-forcereact-android
      - build-forceios
      - build-forcehybrid-ios
      - build-forcereact-ios

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~8:30pm Sunday/Wednesday Nights
  weekly-build-all-apps:
    triggers:
      - schedule:
          cron: "30 4 * * 2,4,6"
          filters:
            branches:
              only:
                - dev
    jobs:
      - build-forcedroid
      - build-forcehybrid-android
      - build-forcereact-android
      - build-forceios
      - build-forcehybrid-ios
      - build-forcereact-ios
